/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uasppbo;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author farha
 */
public class Buku extends javax.swing.JFrame {
    DefaultTableModel model;
    
    /**
     * Creates new form Buku
     */
    public Buku() {
        initComponents();
        String [] judul = {"ISBN", "JUDUL BUKU", "PENGARANG", "PENERBIT", "TAHUN TERBIT"};
        model = new DefaultTableModel(judul,0);
        tabel.setModel(model);
        tampilkan();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ISBN = new javax.swing.JTextField();
        Judul_Buku = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Pengarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Penerbit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        Tahun_Terbit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA BUKU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, 960, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ISBN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 111, -1, -1));

        ISBN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBNActionPerformed(evt);
            }
        });
        getContentPane().add(ISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 102, 340, 31));

        Judul_Buku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Judul_Buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Judul_BukuActionPerformed(evt);
            }
        });
        getContentPane().add(Judul_Buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 142, 340, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Judul Buku");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 142, -1, -1));

        Pengarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Pengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PengarangActionPerformed(evt);
            }
        });
        getContentPane().add(Pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 180, 340, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Pengarang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 180, -1, -1));

        Penerbit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenerbitActionPerformed(evt);
            }
        });
        getContentPane().add(Penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 218, 340, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Penerbit");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 220, -1, -1));

        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        getContentPane().add(btnubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 308, 82, 45));

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 308, 86, 45));

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 308, 87, 45));

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        getContentPane().add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 308, 100, 45));

        Tahun_Terbit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tahun_Terbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tahun_TerbitActionPerformed(evt);
            }
        });
        getContentPane().add(Tahun_Terbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 264, 340, 28));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tahun Terbit");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 266, -1, -1));

        tabel.setAutoCreateRowSorter(true);
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.setAlignmentX(2.0F);
        tabel.setAlignmentY(2.0F);
        tabel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabel.setAutoscrolls(false);
        tabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 372, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBNActionPerformed

    private void Judul_BukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Judul_BukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Judul_BukuActionPerformed

    private void PengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PengarangActionPerformed

    private void PenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PenerbitActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        try {
            // TODO add your handling code here:
            Connection cn  = DriverManager.getConnection("jdbc:mysql://localhost/buku","root","");
            cn.createStatement().executeUpdate("update databuku set ISBN ='"+ISBN.getText()+"' ,Judul_Buku ='"+Judul_Buku.getText()+"',Pengarang = '"+Pengarang.getText()+"',Penerbit = '"+Penerbit.getText()+"',Tahun_Terbit = '"+Tahun_Terbit.getText()+"' WHERE ISBN = '"+ISBN.getText()+"' " );
            tampilkan();
            reset();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
        }
        
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        try {
            Connection cn  = DriverManager.getConnection("jdbc:mysql://localhost/buku","root","");
            cn.createStatement().executeUpdate("delete from databuku where ISBN = '"+ISBN.getText()+"'");
            tampilkan();
            reset();
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
        }
    }//GEN-LAST:event_btnhapusActionPerformed
    private void reset(){
        ISBN.setText("");
        Judul_Buku.setText("");
        Penerbit.setText("");
        Pengarang.setText("");
        Tahun_Terbit.setText("");
    }
    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        reset();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        try {
            // TODO add your handling code here:
            Connection cn  = DriverManager.getConnection("jdbc:mysql://localhost/buku","root","");
            cn.createStatement().executeUpdate("insert into databuku values" + "('"+ISBN.getText()+"','"+Judul_Buku.getText()+"','"+Pengarang.getText()+"','"+Penerbit.getText()+"','"+Tahun_Terbit.getText()+"')");
            tampilkan();
            reset();
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        int i = tabel.getSelectedRow();
        if(i>=0){
            ISBN.setText(model.getValueAt(i, 0).toString());
            Judul_Buku.setText(model.getValueAt(i, 1).toString());
            Pengarang.setText(model.getValueAt(i, 2).toString());
            Penerbit.setText(model.getValueAt(i, 3).toString());
            Tahun_Terbit.setText(model.getValueAt(i, 4).toString());
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void Tahun_TerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tahun_TerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tahun_TerbitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ISBN;
    private javax.swing.JTextField Judul_Buku;
    private javax.swing.JTextField Penerbit;
    private javax.swing.JTextField Pengarang;
    private javax.swing.JTextField Tahun_Terbit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
    private void tampilkan() {
        int row = tabel.getRowCount();
        for (int a = 0; a<row; a++){
               model.removeRow(0);
        }
        try {
            Connection cn  = DriverManager.getConnection("jdbc:mysql://localhost/buku","root","");
            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM databuku");
            while(rs.next()){
                String data []= {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                model.addRow(data);
            }  
        } catch (SQLException ex) {
            Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buku().setVisible(true);
            }
        });
    }
}
